name: example-rust-hello-world
version: "1.0"
summary: Say hello world with Rust.
description: Creates a simple hello world snap using Rust.

grade: devel
base: core20
confinement: strict

apps:
  example-rust-hello-world:
    command: bin/rust-hello

parts:
  hello:
    plugin: rust
    source: .
